config/routes.rb
Rails.application.routes.draw do
  resources :widgets
  get 'session/index'

  get 'login' => 'session#login_attempt'

  get 'session/logout'

  get 'session/create'

  get 'home/index'

  root :to => 'session#index'

  resources :users
  resources :tickets, shallow: true do
    member do
      get 'active'
    end
  end
  resources :settings
  resources :roles
  resources :provinsis, shallow: true do
    member do
      get 'active'
    end
  end
  resources :profiles, shallow: true do
    member do
      delete 'delete_image'
    end
  end
  resources :products, shallow: true do
    member do
      get 'active'
    end
  end
  resources :pages, shallow: true do
    member do
      get 'active'
    end
  end
  resources :kota, shallow: true do
    member do
      get 'active'
    end
  end
  resources :conversations
  resources :contacts
  resources :categories
  resources :blogs, shallow: true do
    member do
      get 'active'
    end
  end
  post 'uploads' => 'upload#create'
  post 'send-message' => 'tickets#send_message'
  post 'get-message' => 'tickets#get_message'
  post 'login' => 'session#login_attempt'
  get 'logout' => 'session#logout'
  post 'logout' => 'session#logout'

end

app/models/blog.rb
class Blog < ActiveRecord::Base
end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
end

app/models/kotum.rb
class Kotum < ActiveRecord::Base
end

app/models/page.rb
class Page < ActiveRecord::Base
end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/models/profile.rb
class Profile < ActiveRecord::Base
end

app/models/provinsi.rb
class Provinsi < ActiveRecord::Base
end

app/models/role.rb
class Role < ActiveRecord::Base
end

app/models/setting.rb
class Setting < ActiveRecord::Base
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :password,:password_confirmation,:updating_password #,:role_id #, :skip_password #, :skip_lpassword_validation

  EMAIL_REGEX = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
  validates :username, :presence => true, :uniqueness => true, :length => { :in => 3..20 }
  validates :email, :presence => true, :uniqueness => true, :format => EMAIL_REGEX
  validates :password, :confirmation => true,:if => :should_validate_password? #, :on => :create #password_confirmation attr
  validates_length_of :password, :in => 6..20 ,:if => :should_validate_password? #, :on => :create
  validates_presence_of :role_id,:if => :pilih_role_validate?,:message => "Harus dipilih!"

  before_save :encrypt_password
  # before_save :default_values_set
  #
  before_update :encrypt_password
  after_save :clear_password
  # after_save :default_values_set

 # # User
  belongs_to :role
  has_many :profiles,dependent: :destroy
  has_many :product,dependent: :destroy
  has_many :blogs,dependent: :destroy
  has_many :ticket,dependent: :destroy
  has_many :conversation, dependent: :destroy

  def self.from_omniauth(auth,password)
    User.where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.username = auth.info.name
      user.email = auth.info.email
      user.password = password
      user.role_id = 3
      user.is_active = 1
      user.save!(:validate => false)


    end
  end

  def name_with_initial
    "#{id}. #{name}"
  end

  def should_validate_password?
    updating_password || new_record?
  end

  def pilih_role_validate?
    role_id || new_record?
  end

  #cari data
  def self.search(search)
    if search
      self.where('username LIKE ? or email LIKE ?',"%#{search}%","%#{search}%")
    else
      self.all
      # find(:all)
      # order('id desc')
    end
  end

 # check password
 def self.check_password(current_password,userid)
    user = User.find_by_id(userid)
    pass = BCrypt::Engine.hash_secret(current_password, user.salt)
    if user && user.encrypted_password == pass
      return true
    else
      return pass + " / " + user.encrypted_password + " / " + current_password
    end
  end

  # authenticate proses
	def encrypt_password
	  if password.present?
	    self.salt = BCrypt::Engine.generate_salt
	    self.encrypted_password= BCrypt::Engine.hash_secret(password, salt)
	  end
	end

  # clear password
	def clear_password
	  self.password = nil
	end

  # login
  def self.authenticate(username_or_email="",password="")

    if  EMAIL_REGEX.match(username_or_email)
      user = User.find_by_email(username_or_email)

    else
      user = User.find_by_username(username_or_email)

    end

    if user && user.encrypted_password == BCrypt::Engine.hash_secret(password, user.salt)
      return user
    else
      return false
    end
  end

  # check it up
  def check_active_user(username_or_email)
    if  EMAIL_REGEX.match(username_or_email)
      user = User.find_by_email(username_or_email)
    else
      user = User.find_by_username(username_or_email)
    end
    active = user.is_active
    return active
  end
end

app/models/widget.rb
class Widget < ActiveRecord::Base
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :set_conversation, only: [:show, :edit, :update, :destroy]

  # GET /conversations
  # GET /conversations.json
  def index
    @conversations = Conversation.all
  end

  # GET /conversations/1
  # GET /conversations/1.json
  def show
  end

  # GET /conversations/new
  def new
    @conversation = Conversation.new
  end

  # GET /conversations/1/edit
  def edit
  end

  # POST /conversations
  # POST /conversations.json
  def create
    @conversation = Conversation.new(conversation_params)

    respond_to do |format|
      if @conversation.save
        format.html { redirect_to @conversation, notice: 'Conversation was successfully created.' }
        format.json { render :show, status: :created, location: @conversation }
      else
        format.html { render :new }
        format.json { render json: @conversation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /conversations/1
  # PATCH/PUT /conversations/1.json
  def update
    respond_to do |format|
      if @conversation.update(conversation_params)
        format.html { redirect_to @conversation, notice: 'Conversation was successfully updated.' }
        format.json { render :show, status: :ok, location: @conversation }
      else
        format.html { render :edit }
        format.json { render json: @conversation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /conversations/1
  # DELETE /conversations/1.json
  def destroy
    @conversation.destroy
    respond_to do |format|
      format.html { redirect_to conversations_url, notice: 'Conversation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_conversation
      @conversation = Conversation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def conversation_params
      params.require(:conversation).permit(:id, :ticket_id, :avatar, :numbering, :user_id, :message, :is_read)
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/kota_helper.rb
module KotaHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/secret_helper.rb
module SecretHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/conversations/_form.html.erb
<%= form_for(@conversation) do |f| %>
  <% if @conversation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@conversation.errors.count, "error") %> prohibited this conversation from being saved:</h2>

      <ul>
      <% @conversation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br>
    <%= f.text_field :id %>
  </div>
  <div class="field">
    <%= f.label :ticket_id %><br>
    <%= f.text_field :ticket_id %>
  </div>
  <div class="field">
    <%= f.label :avatar %><br>
    <%= f.text_field :avatar %>
  </div>
  <div class="field">
    <%= f.label :numbering %><br>
    <%= f.text_field :numbering %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :message %><br>
    <%= f.text_area :message %>
  </div>
  <div class="field">
    <%= f.label :is_read %><br>
    <%= f.check_box :is_read %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/conversations/edit.html.erb
<h1>Editing Conversation</h1>

<%= render 'form' %>

<%= link_to 'Show', @conversation %> |
<%= link_to 'Back', conversations_path %>

app/views/conversations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Conversations</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Ticket</th>
      <th>Avatar</th>
      <th>Numbering</th>
      <th>User</th>
      <th>Message</th>
      <th>Is read</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @conversations.each do |conversation| %>
      <tr>
        <td><%= conversation.id %></td>
        <td><%= conversation.ticket_id %></td>
        <td><%= conversation.avatar %></td>
        <td><%= conversation.numbering %></td>
        <td><%= conversation.user_id %></td>
        <td><%= conversation.message %></td>
        <td><%= conversation.is_read %></td>
        <td><%= link_to 'Show', conversation %></td>
        <td><%= link_to 'Edit', edit_conversation_path(conversation) %></td>
        <td><%= link_to 'Destroy', conversation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Conversation', new_conversation_path %>

app/views/conversations/new.html.erb
<h1>New Conversation</h1>

<%= render 'form' %>

<%= link_to 'Back', conversations_path %>

app/views/conversations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @conversation.id %>
</p>

<p>
  <strong>Ticket:</strong>
  <%= @conversation.ticket_id %>
</p>

<p>
  <strong>Avatar:</strong>
  <%= @conversation.avatar %>
</p>

<p>
  <strong>Numbering:</strong>
  <%= @conversation.numbering %>
</p>

<p>
  <strong>User:</strong>
  <%= @conversation.user_id %>
</p>

<p>
  <strong>Message:</strong>
  <%= @conversation.message %>
</p>

<p>
  <strong>Is read:</strong>
  <%= @conversation.is_read %>
</p>

<%= link_to 'Edit', edit_conversation_path(@conversation) %> |
<%= link_to 'Back', conversations_path %>