config/routes.rb
Rails.application.routes.draw do
  resources :widgets
  get 'session/index'

  get 'login' => 'session#login_attempt'

  get 'session/logout'

  get 'session/create'

  get 'home/index'

  root :to => 'session#index'

  resources :users
  resources :tickets, shallow: true do
    member do
      get 'active'
    end
  end
  resources :settings
  resources :roles
  resources :provinsis, shallow: true do
    member do
      get 'active'
    end
  end
  resources :profiles, shallow: true do
    member do
      delete 'delete_image'
    end
  end
  resources :products, shallow: true do
    member do
      get 'active'
    end
  end
  resources :pages, shallow: true do
    member do
      get 'active'
    end
  end
  resources :kota, shallow: true do
    member do
      get 'active'
    end
  end
  resources :conversations
  resources :contacts
  resources :categories
  resources :blogs, shallow: true do
    member do
      get 'active'
    end
  end
  post 'uploads' => 'upload#create'
  post 'send-message' => 'tickets#send_message'
  post 'get-message' => 'tickets#get_message'
  post 'login' => 'session#login_attempt'
  get 'logout' => 'session#logout'
  post 'logout' => 'session#logout'

end

app/models/blog.rb
class Blog < ActiveRecord::Base
end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
end

app/models/kotum.rb
class Kotum < ActiveRecord::Base
end

app/models/page.rb
class Page < ActiveRecord::Base
end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/models/profile.rb
class Profile < ActiveRecord::Base
end

app/models/provinsi.rb
class Provinsi < ActiveRecord::Base
end

app/models/role.rb
class Role < ActiveRecord::Base
end

app/models/setting.rb
class Setting < ActiveRecord::Base
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :password,:password_confirmation,:updating_password #,:role_id #, :skip_password #, :skip_lpassword_validation

  EMAIL_REGEX = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
  validates :username, :presence => true, :uniqueness => true, :length => { :in => 3..20 }
  validates :email, :presence => true, :uniqueness => true, :format => EMAIL_REGEX
  validates :password, :confirmation => true,:if => :should_validate_password? #, :on => :create #password_confirmation attr
  validates_length_of :password, :in => 6..20 ,:if => :should_validate_password? #, :on => :create
  validates_presence_of :role_id,:if => :pilih_role_validate?,:message => "Harus dipilih!"

  before_save :encrypt_password
  # before_save :default_values_set
  #
  before_update :encrypt_password
  after_save :clear_password
  # after_save :default_values_set

 # # User
  belongs_to :role
  has_many :profiles,dependent: :destroy
  has_many :product,dependent: :destroy
  has_many :blogs,dependent: :destroy
  has_many :ticket,dependent: :destroy
  has_many :conversation, dependent: :destroy

  def self.from_omniauth(auth,password)
    User.where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.username = auth.info.name
      user.email = auth.info.email
      user.password = password
      user.role_id = 3
      user.is_active = 1
      user.save!(:validate => false)


    end
  end

  def name_with_initial
    "#{id}. #{name}"
  end

  def should_validate_password?
    updating_password || new_record?
  end

  def pilih_role_validate?
    role_id || new_record?
  end

  #cari data
  def self.search(search)
    if search
      self.where('username LIKE ? or email LIKE ?',"%#{search}%","%#{search}%")
    else
      self.all
      # find(:all)
      # order('id desc')
    end
  end

 # check password
 def self.check_password(current_password,userid)
    user = User.find_by_id(userid)
    pass = BCrypt::Engine.hash_secret(current_password, user.salt)
    if user && user.encrypted_password == pass
      return true
    else
      return pass + " / " + user.encrypted_password + " / " + current_password
    end
  end

  # authenticate proses
	def encrypt_password
	  if password.present?
	    self.salt = BCrypt::Engine.generate_salt
	    self.encrypted_password= BCrypt::Engine.hash_secret(password, salt)
	  end
	end

  # clear password
	def clear_password
	  self.password = nil
	end

  # login
  def self.authenticate(username_or_email="",password="")

    if  EMAIL_REGEX.match(username_or_email)
      user = User.find_by_email(username_or_email)

    else
      user = User.find_by_username(username_or_email)

    end

    if user && user.encrypted_password == BCrypt::Engine.hash_secret(password, user.salt)
      return user
    else
      return false
    end
  end

  # check it up
  def check_active_user(username_or_email)
    if  EMAIL_REGEX.match(username_or_email)
      user = User.find_by_email(username_or_email)
    else
      user = User.find_by_username(username_or_email)
    end
    active = user.is_active
    return active
  end
end

app/models/widget.rb
class Widget < ActiveRecord::Base
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  before_action :set_setting, only: [:show, :edit, :update, :destroy]

  # GET /settings
  # GET /settings.json
  def index
    @settings = Setting.all
  end

  # GET /settings/1
  # GET /settings/1.json
  def show
  end

  # GET /settings/new
  def new
    @setting = Setting.new
  end

  # GET /settings/1/edit
  def edit
  end

  # POST /settings
  # POST /settings.json
  def create
    @setting = Setting.new(setting_params)

    respond_to do |format|
      if @setting.save
        format.html { redirect_to @setting, notice: 'Setting was successfully created.' }
        format.json { render :show, status: :created, location: @setting }
      else
        format.html { render :new }
        format.json { render json: @setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /settings/1
  # PATCH/PUT /settings/1.json
  def update
    respond_to do |format|
      if @setting.update(setting_params)
        format.html { redirect_to @setting, notice: 'Setting was successfully updated.' }
        format.json { render :show, status: :ok, location: @setting }
      else
        format.html { render :edit }
        format.json { render json: @setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /settings/1
  # DELETE /settings/1.json
  def destroy
    @setting.destroy
    respond_to do |format|
      format.html { redirect_to settings_url, notice: 'Setting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_setting
      @setting = Setting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def setting_params
      params.require(:setting).permit(:id, :nama_aplikasi, :email_default, :alamat, :default_password, :zopim, :site_status)
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/kota_helper.rb
module KotaHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/secret_helper.rb
module SecretHelper
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/settings/_form.html.erb
<%= form_for(@setting) do |f| %>
  <% if @setting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@setting.errors.count, "error") %> prohibited this setting from being saved:</h2>

      <ul>
      <% @setting.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br>
    <%= f.text_field :id %>
  </div>
  <div class="field">
    <%= f.label :nama_aplikasi %><br>
    <%= f.text_field :nama_aplikasi %>
  </div>
  <div class="field">
    <%= f.label :email_default %><br>
    <%= f.text_field :email_default %>
  </div>
  <div class="field">
    <%= f.label :alamat %><br>
    <%= f.text_area :alamat %>
  </div>
  <div class="field">
    <%= f.label :default_password %><br>
    <%= f.text_field :default_password %>
  </div>
  <div class="field">
    <%= f.label :zopim %><br>
    <%= f.check_box :zopim %>
  </div>
  <div class="field">
    <%= f.label :site_status %><br>
    <%= f.check_box :site_status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/settings/edit.html.erb
<h1>Editing Setting</h1>

<%= render 'form' %>

<%= link_to 'Show', @setting %> |
<%= link_to 'Back', settings_path %>

app/views/settings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Settings</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Nama aplikasi</th>
      <th>Email default</th>
      <th>Alamat</th>
      <th>Default password</th>
      <th>Zopim</th>
      <th>Site status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @settings.each do |setting| %>
      <tr>
        <td><%= setting.id %></td>
        <td><%= setting.nama_aplikasi %></td>
        <td><%= setting.email_default %></td>
        <td><%= setting.alamat %></td>
        <td><%= setting.default_password %></td>
        <td><%= setting.zopim %></td>
        <td><%= setting.site_status %></td>
        <td><%= link_to 'Show', setting %></td>
        <td><%= link_to 'Edit', edit_setting_path(setting) %></td>
        <td><%= link_to 'Destroy', setting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Setting', new_setting_path %>

app/views/settings/new.html.erb
<h1>New Setting</h1>

<%= render 'form' %>

<%= link_to 'Back', settings_path %>

app/views/settings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @setting.id %>
</p>

<p>
  <strong>Nama aplikasi:</strong>
  <%= @setting.nama_aplikasi %>
</p>

<p>
  <strong>Email default:</strong>
  <%= @setting.email_default %>
</p>

<p>
  <strong>Alamat:</strong>
  <%= @setting.alamat %>
</p>

<p>
  <strong>Default password:</strong>
  <%= @setting.default_password %>
</p>

<p>
  <strong>Zopim:</strong>
  <%= @setting.zopim %>
</p>

<p>
  <strong>Site status:</strong>
  <%= @setting.site_status %>
</p>

<%= link_to 'Edit', edit_setting_path(@setting) %> |
<%= link_to 'Back', settings_path %>